async function updateScoutingData() {
	//TODO: put code here to get scouting data from website
	return {
		data: [
			{
				primary_key: "118-2024txcmp1_qm1-blue1-Saragh E",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm1",
				driver_station: "blue1",
				comp_level: "qm",
				match_number: 1,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 2,
				auto_midfield_pickups: 1,
				tele_amp: 3,
				tele_amp_miss: 0,
				tele_speaker: 2,
				tele_speaker_miss: 5,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Saragh E",
				tele_assist: 4,
			},
			{
				primary_key: "118-2024txcmp1_qm18-red3-Ryan R",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm18",
				driver_station: "red3",
				comp_level: "qm",
				match_number: 18,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 3,
				auto_midfield_pickups: 1,
				tele_amp: 5,
				tele_amp_miss: 0,
				tele_speaker: 6,
				tele_speaker_miss: 1,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Ryan R",
				tele_assist: 1,
			},
			{
				primary_key: "118-2024txcmp1_qm24-blue1-Chance P",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm24",
				driver_station: "blue1",
				comp_level: "qm",
				match_number: 24,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 4,
				auto_midfield_pickups: 2,
				tele_amp: 7,
				tele_amp_miss: 0,
				tele_speaker: 6,
				tele_speaker_miss: 1,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Chance P",
				tele_assist: 0,
			},
			{
				primary_key: "118-2024txcmp1_qm40-red3-Josh W",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm40",
				driver_station: "red3",
				comp_level: "qm",
				match_number: 40,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 1,
				auto_midfield_pickups: 1,
				tele_amp: 5,
				tele_amp_miss: 0,
				tele_speaker: 5,
				tele_speaker_miss: 1,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Josh W",
				tele_assist: 2,
			},
			{
				primary_key: "118-2024txcmp1_qm50-red3-Hitu C",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm50",
				driver_station: "red3",
				comp_level: "qm",
				match_number: 50,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 3,
				auto_midfield_pickups: 1,
				tele_amp: 5,
				tele_amp_miss: 0,
				tele_speaker: 8,
				tele_speaker_miss: 1,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 3,
				mech_failure: " ",
				scouted_by: "Hitu C",
				tele_assist: 2,
			},
			{
				primary_key: "118-2024txcmp1_qm58-red1-Shelby M",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm58",
				driver_station: "red1",
				comp_level: "qm",
				match_number: 58,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 2,
				auto_midfield_pickups: 1,
				tele_amp: 0,
				tele_amp_miss: 0,
				tele_speaker: 4,
				tele_speaker_miss: 0,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Shelby M",
				tele_assist: 0,
			},
			{
				primary_key: "118-2024txcmp1_qm63-red1-Victoria H",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm63",
				driver_station: "red1",
				comp_level: "qm",
				match_number: 63,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 3,
				auto_midfield_pickups: 2,
				tele_amp: 2,
				tele_amp_miss: 0,
				tele_speaker: 0,
				tele_speaker_miss: 0,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Victoria H",
				tele_assist: 0,
			},
			{
				primary_key: "118-2024txcmp1_qm70-red2-Clyde D",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm70",
				driver_station: "red2",
				comp_level: "qm",
				match_number: 70,
				auto_moved: " ",
				auto_amp: 0,
				auto_speaker: 1,
				auto_midfield_pickups: 0,
				tele_amp: 0,
				tele_amp_miss: 0,
				tele_speaker: 11,
				tele_speaker_miss: 0,
				tele_trap: 1,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Clyde D",
				tele_assist: 5,
			},
			{
				primary_key: "118-2024txcmp1_qm78-blue2-Shelby M",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm78",
				driver_station: "blue2",
				comp_level: "qm",
				match_number: 78,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 2,
				auto_midfield_pickups: 1,
				tele_amp: 0,
				tele_amp_miss: 0,
				tele_speaker: 4,
				tele_speaker_miss: 0,
				tele_trap: 0,
				tele_climb: " ",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Shelby M",
				tele_assist: 0,
			},
			{
				primary_key: "118-2024txcmp1_qm83-blue2-Shelby M",
				frc_team: "118",
				event_key: "2024txcmp1",
				match_key: "2024txcmp1_qm83",
				driver_station: "blue2",
				comp_level: "qm",
				match_number: 83,
				auto_moved: "Yes",
				auto_amp: 0,
				auto_speaker: 1,
				auto_midfield_pickups: 2,
				tele_amp: 9,
				tele_amp_miss: 0,
				tele_speaker: 8,
				tele_speaker_miss: 2,
				tele_trap: 0,
				tele_climb: "Climb",
				defender_rating: 0,
				mech_failure: " ",
				scouted_by: "Shelby M",
				tele_assist: 0,
			},
			{
				"primary_key": "1477-2024txcmp1_qm10-red3-Carter N",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm10",
				"driver_station": "red3",
				"comp_level": "qm",
				"match_number": 10,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 3,
				"auto_midfield_pickups": 0,
				"tele_amp": 0,
				"tele_amp_miss": 0,
				"tele_speaker": 0,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Carter N",
				"tele_assist": 9
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm20-blue1-Clyde D",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm20",
				"driver_station": "blue1",
				"comp_level": "qm",
				"match_number": 20,
				"auto_moved": "No",
				"auto_amp": 0,
				"auto_speaker": 4,
				"auto_midfield_pickups": 1,
				"tele_amp": 7,
				"tele_amp_miss": 0,
				"tele_speaker": 5,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Clyde D",
				"tele_assist": 2
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm27-red2-Jared CF",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm27",
				"driver_station": "red2",
				"comp_level": "qm",
				"match_number": 27,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 2,
				"auto_midfield_pickups": 1,
				"tele_amp": 2,
				"tele_amp_miss": 0,
				"tele_speaker": 11,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Harmony",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Jared CF",
				"tele_assist": 2
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm3-blue2-Shelby M",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm3",
				"driver_station": "blue2",
				"comp_level": "qm",
				"match_number": 3,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 4,
				"auto_midfield_pickups": 0,
				"tele_amp": 1,
				"tele_amp_miss": 0,
				"tele_speaker": 6,
				"tele_speaker_miss": 4,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Shelby M",
				"tele_assist": 0
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm37-red1-Carter N",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm37",
				"driver_station": "red1",
				"comp_level": "qm",
				"match_number": 37,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 2,
				"auto_midfield_pickups": 1,
				"tele_amp": 1,
				"tele_amp_miss": 0,
				"tele_speaker": 2,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Carter N",
				"tele_assist": 11
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm49-blue3-Chance P",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm49",
				"driver_station": "blue3",
				"comp_level": "qm",
				"match_number": 49,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 3,
				"auto_midfield_pickups": 0,
				"tele_amp": 1,
				"tele_amp_miss": 1,
				"tele_speaker": 6,
				"tele_speaker_miss": 0,
				"tele_trap": 1,
				"tele_climb": "Climb",
				"defender_rating": 1,
				"mech_failure": " ",
				"scouted_by": "Chance P",
				"tele_assist": 3
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm54-blue2-Benjamin H",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm54",
				"driver_station": "blue2",
				"comp_level": "qm",
				"match_number": 54,
				"auto_moved": " ",
				"auto_amp": 0,
				"auto_speaker": 3,
				"auto_midfield_pickups": 0,
				"tele_amp": 5,
				"tele_amp_miss": 1,
				"tele_speaker": 4,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Benjamin H",
				"tele_assist": 3
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm60-blue3-Kai G",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm60",
				"driver_station": "blue3",
				"comp_level": "qm",
				"match_number": 60,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 5,
				"auto_midfield_pickups": 0,
				"tele_amp": 1,
				"tele_amp_miss": 0,
				"tele_speaker": 6,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Harmony",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Kai G",
				"tele_assist": 5
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm66-blue1-Hitu C",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm66",
				"driver_station": "blue1",
				"comp_level": "qm",
				"match_number": 66,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 4,
				"auto_midfield_pickups": 1,
				"tele_amp": 5,
				"tele_amp_miss": 6,
				"tele_speaker": 4,
				"tele_speaker_miss": 1,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 1,
				"mech_failure": " ",
				"scouted_by": "Hitu C",
				"tele_assist": 0
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm73-red3-Benjamin H",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm73",
				"driver_station": "red3",
				"comp_level": "qm",
				"match_number": 73,
				"auto_moved": " ",
				"auto_amp": 0,
				"auto_speaker": 5,
				"auto_midfield_pickups": 0,
				"tele_amp": 4,
				"tele_amp_miss": 0,
				"tele_speaker": 5,
				"tele_speaker_miss": 0,
				"tele_trap": 1,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Benjamin H",
				"tele_assist": 2
			  },
			  {
				"primary_key": "1477-2024txcmp1_qm80-red1-Chance P",
				"frc_team": "1477",
				"event_key": "2024txcmp1",
				"match_key": "2024txcmp1_qm80",
				"driver_station": "red1",
				"comp_level": "qm",
				"match_number": 80,
				"auto_moved": "Yes",
				"auto_amp": 0,
				"auto_speaker": 1,
				"auto_midfield_pickups": 1,
				"tele_amp": 4,
				"tele_amp_miss": 2,
				"tele_speaker": 4,
				"tele_speaker_miss": 0,
				"tele_trap": 0,
				"tele_climb": "Climb",
				"defender_rating": 0,
				"mech_failure": " ",
				"scouted_by": "Chance P",
				"tele_assist": 1
			  }
		],
	};
}

function getTeamScoutData(team_num) {
	filtered_data = scouting_data.data.filter(
		(team) => team.frc_team == team_num,
	);
	return filtered_data;
}

function setup_graph(scouting_data) {
	var data = [];
	var scouters = [];
	for (let j = 0; j < scouting_data.length; j++) {
		scouters.push(scouting_data[j].scouted_by);
	}
	var trace = {
		x: [],
		y: [],
		text: [],
		customdata: scouters,
		hovertemplate:
			"<i>Notes</i>: %{y}" + "<br><i>Scouter</i>: %{customdata}</br>",
		name: current_stat,
		type: "bar",
	};
	for (let j = 0; j < scouting_data.length; j++) {
		trace.x.push("(".concat(scouting_data[j].match_number, ")"));
		trace.y.push(scouting_data[j][current_stat]);
		trace.text.push(scouting_data[j][current_stat]);
	}
	data.push(trace);

	var container = document.getElementById("graph1");
	var layout = {
		barmode: "group",
		autosize: true,
		width: container.offsetWidth,
		height: container.offsetHeight * 0.9,
		margin: {
			l: 30,
			r: 5,
			b: 45,
			t: 5,
			pad: 4,
		},
		paper_bgcolor: "#252526",
		plot_bgcolor: "#252526",
		barcornerradius: 5,
		showlegend: false,
		xaxis: {
			title: "Qual Matches",
			titlefont: {
				size: 16,
				color: "rgb(150, 150, 150)",
			},
			tickfont: {
				size: 14,
				color: "rgb(150, 150, 150)",
			},
		},

		yaxis: {
			tickfont: {
				size: 14,
				color: "rgb(150, 150, 150)",
			},
		},
	};

	Plotly.newPlot("graph", data, layout, { displayModeBar: false });
}

function updateStatGraph() {
	current_stat = this.value;
	setup_graph(scouting_data);
}

async function getEntries() {
	var key_list = [];
	for (const [key, value] of Object.entries(scouting_data.data[0])) {
		if (typeof value == typeof 0 && key != "match_number") {
			key_list.push(key);
		}
	}
	return key_list;
}

async function setupStatPicker() {
	scouting_data = await updateScoutingData();
	let clone = document.getElementsByTagName("option")[0].cloneNode();
	while (stat_picker.firstChild) {
		stat_picker.firstChild.remove();
	}
	clone.textContent = "None";
	stat_picker.appendChild(clone);
	for (const [key, value] of Object.entries(scouting_data.data[0])) {
		if (typeof value == typeof 0 && key != "match_number") {
			clone = document.getElementsByTagName("option")[0].cloneNode();
			clone.textContent = key;
			stat_picker.appendChild(clone);
		}
	}
}
